language: objective-c
osx_image: xcode7.3

script:
- set -o pipefail && xcodebuild test -workspace Example/AzureNotificationHubClient.xcworkspace -scheme AzureNotificationHubClient-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint

